Andrew/camera2
exspeed/c589-project pull request #7
Opened 2018-01-27 17:35 UTC by exspeed

2018-01-28 20:59 UTC, ammunoz requested changes

2018-01-28 20:59 UTC, ammunoz commented on src/main.cpp
> +    GLFWwindow* window = 0;
minor spacing issue

2018-01-28 20:59 UTC, ammunoz commented on include/Control.h
> +glm::mat4 calculateMVP();
I think Controls should be managed by a class (e.g., ControllerManager or InputManager) and that class should modify a Camera object (and later Geometry). A Scene would then have one or multiple cameras.

2018-01-29 01:03 UTC, DanielDDo approved these changes

2018-01-31 22:04 UTC, merged